---
title: "ENGRD 302W Project Summary"
author: "Veronica"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(tidyverse)
library(ggthemes)
library(dplyr)
```

```{r}
## setting work directory
setwd("C:/Users/13015/OneDrive - Emory University/Documents/Emory/Fall_23/ENGRD 302W/Final Project")
```

```{r}

MUNW <- read.csv("C:/Users/13015/OneDrive - Emory University/Documents/Emory/Fall_23/ENGRD 302W/Final Project/Data/MUNW.csv")

```

```{r}
MUNWAUS <- subset(MUNW, MUNW$Country=="Australia", select=c(Year, Value))

meow <- ggplot(MUNWAUS,aes(x=Year, y=Value))+
    geom_point(size=3, shape=16, color="magenta")+
    geom_smooth(color="blue")+
    labs(x="Year",y="Municipal Waste Generated (Tonnes)",title="Municipal Waste Generated Over Time in Australia")+
    theme_bw()

ggsave("municipal_waste_aus_plot.png", meow)

```

```{r}
MUNWBEL <- subset(MUNW, MUNW$Country=="Belgium", select=c(Year, Value))

ggplot(MUNWBEL,aes(x=Year, y=Value))+
    geom_point(size=3, shape=16, color="orange")+
    geom_smooth(color="blue")+
    labs(x="Year",y="Municipal Waste Generated (Tonnes)",title="Municipal Waste Generated Over Time in Belgium")+
    theme_bw()

```

```{r}
MUNWCAN <- subset(MUNW, MUNW$Country=="Canada", select=c(Year, Value))

ggplot(MUNWCAN,aes(x=Year, y=Value))+
    geom_point(size=3, shape=16, color="red")+
    geom_smooth(color="blue")+
    labs(x="Year",y="Municipal Waste Generated (Tonnes)",title="Municipal Waste Generated Over Time in Canada")+
    theme_bw()

```

```{r}
MUNWCHN <- subset(MUNW, MUNW$Country=="China (People's Republic of)", select=c(Year, Value))

ggplot(MUNWCHN,aes(x=Year, y=Value))+
    geom_point(size=3, shape=16, color="darkgreen")+
    geom_smooth(color="blue")+
    labs(x="Year",y="Municipal Waste Generated (Tonnes)",title="Municipal Waste Generated Over Time in China ")+
    theme_bw()

```

```{r}
MUNWISR <- subset(MUNW, MUNW$Country=="Israel", select=c(Year, Value))

ggplot(MUNWISR,aes(x=Year, y=Value))+
    geom_point(size=3, shape=16, color="coral")+
    geom_smooth(color="blue")+
    labs(x="Year",y="Municipal Waste Generated (Tonnes)",title="Municipal Waste Generated Over Time in Israel")+
    theme_bw()

```

```{r}
MUNWFRA <- subset(MUNW, MUNW$Country=="France", select=c(Year, Value))

ggplot(MUNWFRA,aes(x=Year, y=Value))+
    geom_point(size=3, shape=16, color="limegreen")+
    geom_smooth(color="blue")+
    labs(x="Year",y="Municipal Waste Generated (Tonnes)",title="Municipal Waste Generated Over Time in France")+
    theme_bw()

```

```{r}
MUNWISL <- subset(MUNW, MUNW$Country=="Iceland", select=c(Year, Value))

ggplot(MUNWISL,aes(x=Year, y=Value))+
    geom_point(size=3, shape=16, color="darkorchid")+
    geom_smooth(color="blue")+
    labs(x="Year",y="Municipal Waste Generated (Tonnes)",title="Municipal Waste Generated Over Time in Iceland")+
    theme_bw()

```

```{r}
MUNW1 <- MUNW %>%
  pivot_wider(names_from = "Year", values_from = "Value") %>%
  select("Country", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021") %>%
  group_by(Country) %>%
  summarize("2011" = mean(`2011`, na.rm = TRUE),
    "2012" = mean(`2012`, na.rm = TRUE),
    "2013" = mean(`2013`, na.rm = TRUE),
    "2014" = mean(`2014`, na.rm = TRUE),
    "2015" = mean(`2015`, na.rm = TRUE),
    "2016" = mean(`2016`, na.rm = TRUE),
    "2017" = mean(`2017`, na.rm = TRUE),
    "2018" = mean(`2018`, na.rm = TRUE),
    "2019" = mean(`2019`, na.rm = TRUE),
    "2020" = mean(`2020`, na.rm = TRUE),
    "2021" = mean(`2021`, na.rm = TRUE)) %>%
  na.omit() %>%
  subset(!Country %in% c("OECD - Europe", "OECD - Total", "OECD America", "OECD Asia Oceania"))

write.csv(MUNW1, "C:/Users/13015/Documents/Fall 2023/ENGRD 302W/MUNW1.csv", row.names = FALSE)

```

```{r}
subset1_MUNW1 <- MUNW1 %>%
  select("Country") 

subset1_MUNW1 

num_rows_to_select <- 15 
random_row_indices <- sample(1:nrow(subset1_MUNW1), size = num_rows_to_select)
random_rows <- subset2_MUNW1[random_row_indices, ]
print(random_rows)

representative_sample1 <- MUNW1 %>%
  filter(Country %in% c("Norway", "Costa Rica", "Denmark",  "Luxembourg", "Belgium", "Croatia", "Sweden", "Latvia", "Romania", "Switzerland", "Hungary", "Israel"))

representative_sample_low <- representative_sample1 %>%
  pivot_longer(c("2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021"), names_to = "Year", values_to = "Waste")

representative_plot1 <- ggplot(data = representative_sample_low, aes(x = Year, y = Waste, color = Country)) +
           geom_point() +
           geom_line(aes(group = Country)) +
           labs(x = "Year", y = "Municipal Waste In Tonnes", title = "Municipal Waste Over Time") +
  theme(plot.title = element_text(size = 12)) 

representative_sample2 <- MUNW1 %>%
  filter(Country %in% c("United Kingdom", "France"))

representative_sample_high <- representative_sample2 %>%
  pivot_longer(c("2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021"), names_to = "Year", values_to = "Waste")

representative_plot2 <- ggplot(data = representative_sample_high, aes(x = Year, y = Waste, color = Country)) +
           geom_point() +
           geom_line(aes(group = Country)) +
           labs(x = "Year", y = "Municipal Waste In Tonnes", title = "Municipal Waste Over Time") +
  theme(plot.title = element_text(size = 12)) 

representative_plot1

representative_plot2

ggsave("Representative_Sample_Low.png", representative_plot1, height = 6)

ggsave("Representative_Sample_High.png", representative_plot2)

```

```{r}
random_sample <- MUNW1 %>%
  filter(Country %in% c("Norway", "Costa Rica", "Denmark", "Belarus", "Luxembourg", "Belgium", "Croatia", "Sweden", "Latvia", "Romania", "Switzerland", "Hungary", "Israel", "France", "United Kingdom")) %>%
  pivot_longer(c("2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021"), names_to = "Year", values_to = "Waste") %>%
  select ("Country", "Waste") %>%
  group_by(Country) %>%
  summarize(Average = mean(Waste))

write.csv(random_sample, file = "Average_Municipal_Waste_Randomized_Sample.csv", row.names = FALSE)

```

```{r}
ETD <- read.csv("C:/Users/13015/Documents/Fall 2023/ENGRD 302W/Environmental_Tax_Random_Sample.csv")

ETD <- ETD %>%
  select("LOCATION", "TIME", "Value") %>%
  mutate(Country = fct_recode(LOCATION,
                              "Belgium" = "BEL",
                              "Costa Rica" = "CRI",
                              "Croatia" = "HRV",
                              "Denmark" = "DNK",
                              "Hungary" = "HUN",
                              "Israel" = "ISR",
                              "Latvia" = "LVA",
                              "Luxembourg" = "LUX",
                              "Norway" = "NOR",
                              "Romania" = "ROU",
                              "Sweden" = "SWE",
                              "Switzerland" = "CHE",
                              "France" = "FRA",
                              "United Kingdom" = "GBR")) %>%
           select("Country", "TIME", "Value")
                              
ETD_Fig <- ggplot(data = ETD, aes(x = TIME, y = Value, color = Country)) +
           geom_point() +
           geom_line(aes(group = Country)) +
           labs(x = "Year", y = "Total, % of GDP", title = "Total, % of GDP, 2011-2021")

ggsave("Environmental Tax Data.png", ETD_Fig)
  
  
```

```{r}
MUNWPC <- read.csv("C:/Users/13015/Documents/Fall 2023/ENGRD 302W/MUNW_per_capita.csv")

MUNWPC %>%
  select("COU", "Country", "VAR", "Variable", "Year", "Unit", "PowerCode.Code", "PowerCode", "Value") %>%
  filter(VAR %in% c("DISPOSAL", "HOUSEHOLD", "LANDFILL",))
  pivot_wider(names_from = "Year", values_from = "Value") %>%

```
