---
title: "ENGRD 302W New Data"
author: "Veronica"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Importing Libraries

```{r}
library(ggplot2)
library(tidyverse)
library(ggthemes)
library(dplyr)
library(maps)
library(ggmap)
library(plotly)
library(stringr)
library(lubridate)
library(ggrepel)
```

```{r}
## setting work directory
setwd("C:/Users/13015/OneDrive - Emory University/Documents/Emory/Fall_23/ENGRD 302W/engrd302wfall2023")
```

# Cleaning County Code

```{r}
## loading GA emission data
GAED <- read.csv("C:/Users/13015/OneDrive - Emory University/Documents/Emory/Fall_23/ENGRD 302W/engrd302wfall2023/Data/GAED.csv")

## loading GA county data
GA_counties <- read.csv("C:/Users/13015/OneDrive - Emory University/Documents/Emory/Fall_23/ENGRD 302W/engrd302wfall2023/Data/GA_counties.csv")

## standardizing county code
GA_counties$county_code <- as.character(GA_counties$county_code)
GA_counties$county_name <- tolower(GA_counties$county_name)

GAED <- GAED %>%
  mutate(county_code = gsub("g", "", geocode)) %>%
  select(-geocode)

GAED$county_code <- 
  as.character(GAED$county_code)
head(GAED)

```

## GA County & Time Data

```{r}
## creating GA df
GA_join <- left_join(GAED, GA_counties, by = c("county_code" = "county_code"))

## rename columm
GA_join <- GA_join %>%
  select(-sector, -varname) %>%
  rename("date" = "ldate")

## create date variables
GA_join$date <- as.Date(GA_join$date, "%m/%d/%Y")
GA_join$year <- year(ymd(GA_join$date))
GA_join$month <- month(ymd(GA_join$date)) 
GA_join$day <- day(ymd(GA_join$date))

## subsetting data
GA_join <- GA_join %>%
  select(-date) %>%
  rename("emission_value" = "datavalue") %>%
  filter(year %in% c("2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023"))

## fixing dekalb county
GA_join$county_name <- replace(GA_join$county_name, GA_join$county_name=="de kalb", "dekalb")

head(GA_join)
summary(GA_join)
```

## GA Geographical Data

```{r}
## creating geographical data frame
state_df <- map_data("state") %>%
    filter(region == "georgia")

## creating county data frame
county_df <- map_data("county") %>%
    filter(region == "georgia")

## loading GA population data
GA_population <- read.csv("C:/Users/13015/OneDrive - Emory University/Documents/Emory/Fall_23/ENGRD 302W/engrd302wfall2023/Data/GA_population.csv")

## cleaning population data
GA_population <- GA_population %>%
  select(-X) %>%
  rename("county_name" = "County")

GA_population$county_name <- tolower(GA_population$county_name)

head(GA_population)
```

```{r}
## fixing dekalb county
county_df$subregion <- replace(county_df$subregion, county_df$subregion == "de kalb", "dekalb")

## joining county and population data
GA_geographical <- left_join(GA_population, county_df, by = c("county_name" = "subregion")) %>%
  rename("population" = "Population")

head(GA_geographical)
```

# Data Visualization

```{r}
## mapping GA population data
ggplot(GA_geographical, aes(x=long, y=lat)) +
        geom_polygon(aes(group=group, fill = population), color="yellow") + 
        scale_fill_gradient(low="orange", high="red", trans = "log10") + 
        geom_polygon(data = state_df, aes(group=group), color = "black", fill = NA) + 
        theme_void()+ coord_quickmap()
```

```{r}
## subsetting 2013
GA_2013 <- GA_join %>%
  filter(year %in% c("2013"))
head(GA_2013)
summary(GA_2013)

## subsetting 2023
GA_2023 <- GA_join %>%
  filter(year %in% c("2023"))
head(GA_2023)
summary(GA_2023)
```

## GA Yearly Average County Emission

```{r}
## cleaning GA
GA_join <-  GA_join %>%
  select(emission_value, county_name, year) %>%
  group_by(year, county_name) %>%
  mutate(emission = mean(emission_value)) %>%
  select(-emission_value) %>%
  distinct()
head(GA_join)
```

### Top 10 Emission Production

```{r}
## subsetting top 10 counties
GA_join_top10 <- GA_join %>%
  group_by(county_name) %>%
  summarize(mean(emission)) %>%
  rename("emission" = "mean(emission)") %>%
  arrange(-emission) %>%
  top_n(n = 10, wt = emission)
print(GA_join_top10)
```

## Creating & Plotting Longitudinal Data Frame

```{r}
## subsetting longitudinal data
GA_top10_longitudinal <- GA_join %>%
  filter(county_name %in% c("fulton", "gwinnett", "cobb", "dekalb", "richmond", "chatham", "clayton", "forsyth", "hall", "henry"))

## adding value to each line
df_end <- GA_top10_longitudinal %>%
  filter(year == 2023)

## plotting longitudinal df
ggplot(data = GA_top10_longitudinal,aes(x = year, y = emission, color = county_name)) +
    geom_point() +
    geom_line(aes(group = county_name)) + 
    geom_text_repel(
    aes(label = county_name), data = df_end,
    fontface ="plain", color = "black", size = 3
    ) +
    labs(x="Year",y="Emission Pollution (metric tons)",title= "GA County Emission Pollution 2013-2023") +
    theme_bw() +
    theme(legend.position = "none")
```
